# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  subscriptionId: 26c72f3b-beb6-489d-8bb3-d5f749ab1083

jobs:
  armDeployStaging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-githubactions
      location: Australia East
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy resource group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v2
        with:
          scope : subscription
          subscriptionId: ${{ env.subscriptionId }}
          region : "${{ env.location }}"
          template : ./arm-templates/resourcegroup.json
          parameters:
            location="${{ env.location }}"
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}

      - name: Deploy storage account
        uses: Azure/arm-deploy@v2
        id: storageAccountDeploy
        with:
          scope : resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm-templates/storageaccount.json
          parameters: 
            storageAccountName=djayglobost003
            location="${{ env.location }}"
            sku=standard_LRS
          deploymentMode: incremental

      - name: Deploy virtual machine
        uses: Azure/arm-deploy@v2
        with:
          scope : resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm-templates/vm.json
          parameters: 
            location="${{ env.location }}"
            adminPassword=${{ secrets.WINDOWS_ADMIN_PASSWORD}}
          deploymentMode: incremental
  
  armDeployProduction:
    name: Deploy to production
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-prod-githubactions
      location: Australia Southeast
    environment:
      name: production
    
    needs: armDeployStaging
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy resource group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v2
        with:
          scope : subscription
          subscriptionId: ${{ env.subscriptionId }}
          region : "${{ env.location }}"
          template : ./arm-templates/resourcegroup.json
          parameters:
            location="${{ env.location }}"
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}

      - name: Deploy storage account
        uses: Azure/arm-deploy@v2
        id: storageAccountDeploy
        with:
          scope : resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm-templates/storageaccount.json
          parameters: 
            storageAccountName=djayglobost004
            location="${{ env.location }}"
            sku=standard_LRS
          deploymentMode: incremental

      - name: Deploy virtual machine
        uses: Azure/arm-deploy@v2
        with:
          scope : resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm-templates/vm.json
          parameters: 
            location="${{ env.location }}"
            adminPassword=${{ secrets.WINDOWS_ADMIN_PASSWORD}}
          deploymentMode: incremental