# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy resource gorup rg-githubactions
        uses: Azure/arm-deploy@v2
        with:
          scope : subscription
          subscriptionId: 26c72f3b-beb6-489d-8bb3-d5f749ab1083
          region : Australia East
          template : ./arm-templates/resourcegroup.json
          parameters:
            location="Australia East"
            resourceGroupName=rg-githubactions
          deploymentName: rg-githubactions

      - name: Deploy storage account
        uses: Azure/arm-deploy@v2
        id: storageAccountDeploy
        with:
            scope : resourcegroup
            resourceGroupName: rg-githubactions
            subscriptionId: 26c72f3b-beb6-489d-8bb3-d5f749ab1083
            template: ./arm-templates/storageaccount.json
            parameters: 
              storageAccountName=djayglobost002
              location="Australia Southeast"
              sku=standard_LRS
            deploymentMode: incremental

      - name: Deploy virtual machine
        uses: Azure/arm-deploy@v2
        with:
            scope : resourcegroup
            resourceGroupName: rg-githubactions
            subscriptionId: 26c72f3b-beb6-489d-8bb3-d5f749ab1083
            template: ./arm-templates/virtualmachine.json
            parameters: 
                adminPassword=${{ secrets.UBUNTU_ADMIN_PASSWORD}}
            deploymentMode: incremental