# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy resource gorup rg-githubactions with AZ CLI
        uses: Azure/cli@v2.0.0
        with:
          inlinescript: |
            az deployment sub create --location "Australia East" --template-file ./arm-templates/resourcegroup.json